<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class IplanRpabChecklist extends Model
{
    protected $table = 'iplan_rpab_checklists';

    protected $fillable = [
        'id',
        'userId',
        'subprojectId',
        'reviewDate',
        'percentageAccomplishment',
        'counterpart',
        'geographyStatus',
        'geographyComments',
        'landAreaDescriptionStatus',
        'landAreaDescriptionComments',
        'incomeClassificationStatus',
        'incomeClassificationComments',
        'interestingFactsStatus',
        'interestingFactsComments',
        'briefRuralStatus',
        'briefRuralComments',
        'awardsStatus',
        'awardsComments',
        'visionAgricultureStatus',
        'visionAgricultureComments',
        'totalPopulationStatus',
        'totalPopulationComments',
        'averageHouseholdSizeStatus',
        'averageHouseholdSizeComments',
        'educationPopulationStatus',
        'educationPopulationComments',
        'populationStatus',
        'populationComments',
        'agricultureIncomeStatus',
        'agricultureIncomeComments',
        'incomeDisaggregationStatus',
        'incomeDisaggregationComments',
        'povertyIncidenceStatus',
        'povertyIncidenceComments',
        'availableFacilitiesStatus',
        'availableFacilitiesComments',
        'economicVisionStatus',
        'economicVisionComments',
        'employmentRateStatus',
        'employmentRateComments',
        'priorityCommoditiesStatus',
        'priorityCommoditiesComments',
        'existingMarketsStatus',
        'existingMarketsComments',
        'soilDescriptionStatus',
        'soilDescriptionComments',
        'agriculturalVisionStatus',
        'agriculturalVisionComments',
        'waterResourcesStatus',
        'waterResourcesComments',
        'climateRainfallStatus',
        'climateRainfallComments',
        'enterprisesAvailableStatus',
        'enterprisesAvailableComments',
        'evsaStatus',
        'evsaComments',
        'productionAreaStatus',
        'productionAreaComments',
        'discussConstraintStatus',
        'discussConstraintComments',
        'availableProductFormStatus',
        'availableProductFormComments',
        'discussInterventionStatus',
        'discussInterventionComments',
        'valueAddingMechanismStatus',
        'valueAddingMechanismComments',
        'increaseValueStatus',
        'increaseValueComments',
        'beneficiariesDemographicsStatus',
        'beneficiariesDemographicsComments',
        'numberHouseholdsStatus',
        'numberHouseholdsComments',
        'highlightStatus',
        'highlightComments',
        'commodityAreaStatus',
        'commodityAreaComments',
        'priorityCommoditiesLocationStatus',
        'priorityCommoditiesLocationComments',
        'percentageResidentsStatus',
        'percentageResidentsComments',
        'livingConditionsStatus',
        'livingConditionsComments',
    ];

    use HasFactory;
}
